export type MenuPrice = {
  label?: string;
  value: string;
};

export type MenuItem = {
  number?: string;
  name: string;
  description?: string;
  prices: MenuPrice[];
  markers?: string;
  vegetarian?: boolean;
};

export type MenuCategory = {
  slug: string;
  label: string;
  note?: string;
  items: MenuItem[];
};

const price = (value: string, label?: string): MenuPrice => ({ value, label });
const foodMarkers = "1 · 2 · E · M · N · W";

export const menuCategories: MenuCategory[] = [
  {
    slug: "fingerfood",
    label: "Fingerfood",
    items: [
      { name: "Zaziki mit Fladenbrot", prices: [price("2,00 €")], markers: foodMarkers, vegetarian: true },
      { name: "Schafskäse mit Fladenbrot", prices: [price("3,50 €")], markers: foodMarkers, vegetarian: true },
      { name: "Portion Pommes Frites", prices: [price("4,00 €")], markers: foodMarkers, vegetarian: true },
      {
        name: "Chicken Nuggets",
        description: "Mit Pommes und Salat",
        prices: [price("6,50 €", "6 Stück"), price("7,50 €", "9 Stück")],
        markers: foodMarkers,
      },
      { name: "1 Becher Salatsauce", prices: [price("3,00 €")], markers: foodMarkers, vegetarian: true },
    ],
  },
  {
    slug: "doener",
    label: "Döner",
    note: "Mit Hähnchenfleisch. Alle Döner mit Zaziki, Salatsauce oder scharfer Sauce.",
    items: [
      {
        name: "Pommes Döner",
        description: "Fladenbrot, Pommes, Dönerfleisch und Sauce nach Wahl",
        prices: [price("7,50 €")],
        markers: foodMarkers,
      },
      {
        name: "Vegetarischer Döner",
        description: "Salat, Zwiebeln, Tomaten, Rotkraut, Gurken und Schafskäse",
        prices: [price("6,00 €")],
        markers: foodMarkers,
        vegetarian: true,
      },
      {
        number: "1a",
        name: "Kleiner Döner, Gyros im Fladenbrot",
        description: "Salat, Zwiebeln, Tomaten, Rotkraut und Gurken",
        prices: [price("6,00 €")],
        markers: foodMarkers,
      },
      {
        number: "1",
        name: "Döner, Gyros im Fladenbrot",
        description: "Salat, Zwiebeln, Tomaten, Rotkraut und Gurken",
        prices: [price("7,00 €")],
        markers: foodMarkers,
      },
      {
        number: "1b",
        name: "BIG Döner, Gyros im Fladenbrot",
        description: "Salat, Zwiebeln, Tomaten, Rotkraut und Gurken",
        prices: [price("8,00 €")],
        markers: foodMarkers,
      },
      {
        number: "2",
        name: "Döner, Gyros im Fladenbrot",
        description: "Salat, Zwiebeln, Tomaten, Rotkraut, Gurken und Schafskäse",
        prices: [price("7,50 €")],
        markers: foodMarkers,
      },
      {
        number: "4",
        name: "Döner, Gyrosteller",
        description: "Pommes, Salat, Zwiebeln, Tomaten, Rotkraut und Gurken",
        prices: [price("10,00 €")],
        markers: foodMarkers,
      },
      {
        number: "5",
        name: "Kleiner Dönerteller",
        description: "Pommes, Salat, Zwiebeln, Tomaten, Rotkraut und Gurken",
        prices: [price("8,50 €")],
        markers: foodMarkers,
      },
      {
        number: "6",
        name: "Dönerteller mit Nudeln",
        description: "Salat, Zwiebeln, Tomaten, Rotkraut und Gurken",
        prices: [price("10,00 €")],
        markers: foodMarkers,
      },
      {
        number: "7",
        name: "Dönerteller mit Kroketten",
        description: "Salat, Zwiebeln, Tomaten, Rotkraut und Gurken",
        prices: [price("10,00 €")],
        markers: foodMarkers,
      },
      {
        number: "8",
        name: "Dönerteller",
        description: "Brot, Salat, Zwiebeln, Tomaten, Rotkraut und Gurken",
        prices: [price("10,00 €")],
        markers: foodMarkers,
      },
      {
        number: "9",
        name: "Kleiner Dönerteller",
        description: "Brot, Salat, Zwiebeln, Tomaten, Rotkraut und Gurken",
        prices: [price("7,50 €")],
        markers: foodMarkers,
      },
      {
        number: "10",
        name: "Dönerteller überbacken",
        description: "Gyros, Tomaten, Schafskäse und Sahnesoße, dazu Pommes und Salat",
        prices: [price("11,00 €")],
        markers: foodMarkers,
      },
      {
        number: "11",
        name: "Dönerteller überbacken",
        description: "Gyros, Tomatensoße, Champignons, Paprika, Broccoli und Sahne, dazu Pommes und Salat",
        prices: [price("11,00 €")],
        markers: foodMarkers,
      },
      {
        number: "12",
        name: "Dönerteller Hawaii überbacken",
        description: "Schinken, Gyros, Zwiebeln, Ananas und Sahnesauce, dazu Pommes und Salat",
        prices: [price("11,00 €")],
        markers: foodMarkers,
      },
      {
        number: "13",
        name: "Dönerteller überbacken",
        description: "Paprika, Mais, Gyros, Champignons und Sahnesoße, dazu Pommes und Salat",
        prices: [price("11,00 €")],
        markers: foodMarkers,
      },
      {
        number: "14",
        name: "Dönerbox",
        description: "Salat, Zwiebeln, Tomaten, Rotkraut und Gurken",
        prices: [price("7,00 €")],
        markers: foodMarkers,
      },
      {
        number: "15",
        name: "Dönerbox mit Fleisch und Pommes",
        prices: [price("7,50 €")],
        markers: foodMarkers,
      },
      {
        number: "18",
        name: "Dönerrolle vegetarisch",
        description: "Salat, Zwiebeln, Tomaten, Rotkraut und Gurken",
        prices: [price("6,00 €")],
        markers: foodMarkers,
        vegetarian: true,
      },
      {
        number: "19",
        name: "Dönerrolle mit Fleisch",
        description: "Salat, Zwiebeln, Tomaten, Rotkraut und Gurken",
        prices: [price("7,50 €")],
        markers: foodMarkers,
      },
    ],
  },
  {
    slug: "salate",
    label: "Salate",
    items: [
      { number: "20", name: "Gurkensalat", description: "Rotkraut, Zwiebel, Eisbergsalat, Gurke und Salatsoße", prices: [price("6,00 €")], markers: foodMarkers, vegetarian: true },
      { number: "21", name: "Gemischter Salat", description: "Rotkraut, Zwiebel, Eisbergsalat, Gurke, Tomate und Salatsoße", prices: [price("6,00 €")], markers: foodMarkers, vegetarian: true },
      { number: "22", name: "Gemischter Salat mit Dönerfleisch", description: "Rotkraut, Zwiebel, Eisbergsalat, Gurke, Tomate und Salatsoße", prices: [price("7,50 €")], markers: foodMarkers },
      { number: "23", name: "Gemischter Salat mit Schafskäse", description: "Rotkraut, Zwiebel, Eisbergsalat, Gurke, Tomate und Salatsoße", prices: [price("6,50 €")], markers: foodMarkers, vegetarian: true },
      { number: "24", name: "Mozzarella Salat", description: "Mozzarella, Tomaten, Salat, Zwiebeln und Rotkraut", prices: [price("6,50 €")], markers: foodMarkers, vegetarian: true },
      { number: "25", name: "Gemischter Salat groß mit Dönerfleisch", description: "Rotkraut, Zwiebel, Eisbergsalat, Gurke, Tomate und Salatsoße", prices: [price("8,50 €")], markers: foodMarkers },
      { number: "26", name: "Hawaii Salat", description: "Käse, Schinken, Eisbergsalat, Zwiebeln, Tomaten, Gurken und Ananas", prices: [price("8,50 €")], markers: foodMarkers },
      { number: "27", name: "Thunfischsalat", description: "Gemischter Salat mit Thunfisch", prices: [price("7,50 €")], markers: foodMarkers },
      { number: "28", name: "Tomatensalat", description: "Zwiebeln, Eisbergsalat, Rotkraut, Tomate und Thunfisch", prices: [price("6,50 €")], markers: foodMarkers },
      { number: "29", name: "Italienischer Salat", description: "Gemischter Salat, Tomaten, Gurken, Zwiebeln, Schinken, Käse, Thunfisch und Ei", prices: [price("8,50 €")], markers: foodMarkers },
      { number: "30", name: "Mais mit Putenbrust", description: "Mit Champignons", prices: [price("8,00 €")], markers: foodMarkers },
      { number: "31", name: "Maissalat", description: "Gemischter Salat und Soße", prices: [price("6,50 €")], markers: foodMarkers, vegetarian: true },
      { number: "32", name: "Romana Salat", description: "Gemischter Salat, Thunfisch, Käse, Meeresfrüchte und Salatsoße", prices: [price("8,00 €")], markers: foodMarkers },
      { number: "33", name: "Bauernsalat", description: "Eisbergsalat, Rotkraut, Tomaten, Gurken, Mozzarella, Oliven, Zwiebeln und Käse", prices: [price("8,00 €")], markers: foodMarkers, vegetarian: true },
      { number: "34", name: "Hirtensalat", description: "Gemischter Salat, Peperoni, Oliven und Schafskäse", prices: [price("8,00 €")], markers: foodMarkers, vegetarian: true },
      { number: "35", name: "Salat Hähnchenbruststreifen", description: "Eisbergsalat, Rotkraut, Zwiebeln, Tomaten, Gurken, Paprika, Mais, Hähnchenbruststreifen und Salatsoße", prices: [price("9,00 €")], markers: foodMarkers },
      { number: "36", name: "Salat Hähnchenbruststreifen", description: "Eisbergsalat, Rotkraut, Zwiebel, Gurken, Tomaten, Käse, Hähnchenbruststreifen und Salatsoße", prices: [price("9,00 €")], markers: foodMarkers },
    ],
  },
  {
    slug: "nudeln",
    label: "Nudeln",
    note: "Spaghetti, Rigatoni oder Tortellini. Mit Käse überbacken + 1,00 €.",
    items: [
      { number: "38", name: "Nudeln mit Tomatensoße", prices: [price("7,00 €")], markers: foodMarkers, vegetarian: true },
      { number: "39", name: "Nudeln mit Fleischsoße", prices: [price("8,00 €")], markers: foodMarkers },
      { number: "40", name: "Nudeln mit Mozzarella", description: "Mit Tomatensoße", prices: [price("8,00 €")], markers: foodMarkers, vegetarian: true },
      { number: "41", name: "Nudeln Pasticati", description: "Schinken, Champignons und Sahnesoße", prices: [price("8,00 €")], markers: foodMarkers },
      { number: "42", name: "Nudeln Carbonara", description: "Schinken, Ei und Sahnesauce", prices: [price("8,00 €")], markers: foodMarkers },
      { number: "43", name: "Nudeln Broccoli", description: "Sahne und Broccoli", prices: [price("8,00 €")], markers: foodMarkers, vegetarian: true },
      { number: "44", name: "Nudeln mit Dönerfleisch", description: "Schinken, Sahne, Champignons und Dönerfleisch", prices: [price("8,50 €")], markers: foodMarkers },
      { number: "45", name: "Nudeln Tonno", description: "Tomatensoße, Sahne, Zwiebeln und Thunfisch", prices: [price("8,00 €")], markers: foodMarkers },
      { number: "46", name: "Nudeln mit Würzfleisch", description: "Mit Sahne", prices: [price("8,00 €")], markers: foodMarkers },
      { number: "47", name: "Nudeln Broccoli mit Champignons", description: "Sahnesoße, Zwiebeln und Broccoli", prices: [price("8,00 €")], markers: foodMarkers, vegetarian: true },
      { number: "48", name: "Nudeln Spinat", description: "Sahne, Spinat, Champignons und Ei", prices: [price("8,00 €")], markers: foodMarkers, vegetarian: true },
      { number: "49", name: "Nudeln Spinat mit Dönerfleisch", description: "Schafskäse, Sahne, Spinat, Champignons, Ei und Dönerfleisch", prices: [price("8,50 €")], markers: foodMarkers },
      { number: "50", name: "Nudeln Frutti di Mare", description: "Meeresfrüchte, Knoblauch, Tomaten und Sahnesoße", prices: [price("8,00 €")], markers: foodMarkers },
      { number: "51", name: "Nudeln Krabben", description: "Spinat, Krabben, Knoblauch und Tomatensoße", prices: [price("8,00 €")], markers: foodMarkers },
      { number: "52", name: "Nudeln mit Hähnchenstreifen", description: "Broccoli, Hähnchenstreifen, Mais und Sahnesoße; auf Wunsch auch andere Nudelsorten", prices: [price("8,50 €")], markers: foodMarkers },
      { number: "53", name: "Nudeln Erbsen", description: "Erbsen, Schinken, Champignons und Sahnesoße", prices: [price("8,00 €")], markers: foodMarkers },
    ],
  },
  {
    slug: "burger",
    label: "Burger",
    items: [
      { number: "70", name: "Hamburger 125 g", description: "Eisbergsalat, Gewürzgurken, Tomaten und Soße", prices: [price("6,50 €")], markers: foodMarkers },
      { number: "71", name: "Cheeseburger 125 g", description: "Käse, Eisbergsalat, Gewürzgurken, Tomaten und Soße", prices: [price("7,00 €")], markers: foodMarkers },
    ],
  },
  {
    slug: "auflaeufe",
    label: "Aufläufe",
    note: "Alle Aufläufe werden überbacken und kommen mit einem kleinen Brot.",
    items: [
      { number: "85", name: "Gyros Broccoli Auflauf", description: "Gyros, Broccoli, Champignons, Paprika, Kartoffelstücke und Sahnesoße", prices: [price("9,50 €")], markers: foodMarkers },
      { number: "86", name: "Auflauf Keno Art", description: "Hähnchenbruststreifen, Kartoffelstücke, Knoblauch, Broccoli, Zwiebeln und Sahnesoße", prices: [price("9,50 €")], markers: foodMarkers },
      { number: "87", name: "Vegetarischer Auflauf", description: "Broccoli, Champignons, Spinat, Paprika, Kartoffelstücke und Sahnesoße", prices: [price("9,50 €")], markers: foodMarkers, vegetarian: true },
      { number: "88", name: "Auflauf Hot Chili", description: "Broccoli, Schinken, Hähnchenbruststreifen, Champignons, Chili, Kartoffelstücke und Sahnesoße", prices: [price("9,50 €")], markers: foodMarkers },
      { number: "89", name: "Auflauf Vogtei", description: "Hähnchenbruststreifen, Kartoffelstücke, Knoblauch, Zwiebeln und Sahnesoße", prices: [price("9,50 €")], markers: foodMarkers },
      { number: "90", name: "Schiko", description: "Broccoli, Champignons, Dönerfleisch und Sahnesoße", prices: [price("9,50 €")], markers: foodMarkers },
      { number: "91", name: "Ecape Art", description: "Broccoli, Schinken, Champignons, Kartoffelstücke und Sahnesoße", prices: [price("9,50 €")], markers: foodMarkers },
      { number: "92", name: "Vegetarischer Auflauf", description: "Broccoli, Kartoffelstücke, Champignons, Spinat und Sahnesoße", prices: [price("10,00 €")], markers: foodMarkers, vegetarian: true },
      { number: "93", name: "Mozzo", description: "Broccoli, Hähnchenbruststreifen, Kartoffelstücke, Champignons, Paprika, Mais, Mozzarella und Sahnesoße", prices: [price("10,00 €")], markers: foodMarkers },
    ],
  },
  {
    slug: "pizza",
    label: "Pizza",
    note: "Größen: klein 24 cm · mittel 28 cm · Jumbo 40 cm.",
    items: [
      { name: "Pizzabrot", description: "Knoblauch und Tomatensoße", prices: [price("6,50 €", "28 cm")], markers: foodMarkers, vegetarian: true },
      { number: "94", name: "Pizza Peperoniwurst", description: "Tomatensoße, Käse und Peperoniwurst", prices: [price("7,00 €", "24 cm"), price("8,00 €", "28 cm"), price("13,50 €", "40 cm")], markers: foodMarkers },
      { number: "95", name: "Pizza Margherita", description: "Tomatensoße und Käse", prices: [price("6,50 €", "24 cm"), price("7,50 €", "28 cm"), price("12,00 €", "40 cm")], markers: foodMarkers, vegetarian: true },
      { number: "96", name: "Pizza Salami", description: "Tomatensoße, Käse und Salami", prices: [price("7,00 €", "24 cm"), price("8,00 €", "28 cm"), price("13,50 €", "40 cm")], markers: foodMarkers },
      { number: "97", name: "Pizza Salami-Schinken", description: "Tomatensoße, Käse, Schinken und Salami", prices: [price("7,50 €", "24 cm"), price("8,50 €", "28 cm"), price("14,50 €", "40 cm")], markers: foodMarkers },
      { number: "98", name: "Pizza Schinken", description: "Tomatensoße, Käse und Schinken", prices: [price("7,00 €", "24 cm"), price("8,00 €", "28 cm"), price("13,50 €", "40 cm")], markers: foodMarkers },
      { number: "99", name: "Pizza Schinken mit Ei", description: "Tomatensoße, Käse, Schinken und Ei", prices: [price("7,50 €", "24 cm"), price("8,50 €", "28 cm"), price("14,50 €", "40 cm")], markers: foodMarkers },
      { number: "100", name: "Pizza Champignons", description: "Tomatensoße, Käse und Champignons", prices: [price("7,00 €", "24 cm"), price("8,00 €", "28 cm"), price("13,50 €", "40 cm")], markers: foodMarkers, vegetarian: true },
      { number: "101", name: "Pizza Salami Funghi", description: "Tomatensoße, Käse, Salami und Champignons", prices: [price("7,50 €", "24 cm"), price("8,50 €", "28 cm"), price("14,00 €", "40 cm")], markers: foodMarkers },
      { number: "102", name: "Pizza Schinken Funghi", description: "Tomatensoße, Käse, Schinken und Champignons", prices: [price("7,50 €", "24 cm"), price("8,50 €", "28 cm"), price("14,00 €", "40 cm")], markers: foodMarkers },
      { number: "103", name: "Pizza Del Moro", description: "Tomatensoße, Schinken, Peperoni, Schafskäse und Käse", prices: [price("8,00 €", "24 cm"), price("9,00 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers },
      { number: "104", name: "Pizza Bolognese", description: "Käse und Fleischsoße", prices: [price("7,50 €", "24 cm"), price("8,50 €", "28 cm"), price("14,00 €", "40 cm")], markers: foodMarkers },
      { number: "105", name: "Pizza Bolognese mit Ei", description: "Hackfleisch, Ei und Käse", prices: [price("7,50 €", "24 cm"), price("8,50 €", "28 cm"), price("14,50 €", "40 cm")], markers: foodMarkers },
      { number: "106", name: "Pizza Hawaii", description: "Tomatensoße, Käse, Schinken und Ananas", prices: [price("7,50 €", "24 cm"), price("8,50 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers },
      { number: "107", name: "Pizza Calzone", description: "Tomatensoße, Käse, Salami, Schinken und Champignons", prices: [price("8,00 €", "klein"), price("9,00 €", "mittel")], markers: foodMarkers },
      { number: "107a", name: "Pizza Calzone Würzfleisch", description: "Käse und Würzfleisch", prices: [price("8,50 €", "klein"), price("9,50 €", "mittel")], markers: foodMarkers },
      { number: "108", name: "Pizza Salami-Schinken-Funghi", description: "Tomatensoße, Käse, Salami, Schinken und Champignons", prices: [price("8,00 €", "24 cm"), price("9,00 €", "28 cm"), price("14,50 €", "40 cm")], markers: foodMarkers },
      { number: "108a", name: "Pizza Diavolo", description: "Thunfisch, Salami, Peperoni, Zwiebeln und Oliven", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers },
      { number: "109", name: "Pizza Toscana", description: "Käse, Salami, Schinken, Champignons, Zwiebel und Peperoniwurst", prices: [price("8,00 €", "24 cm"), price("9,00 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers },
      { number: "110", name: "Pizza Chef", description: "Tomatensoße, Käse, Döner-Gyros, Artischocken und Paprika", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers },
      { number: "111", name: "Pizza Elbistan Tasche", description: "Tomatensoße, Käse, Döner-Gyros und Schafskäse", prices: [price("8,50 €", "klein"), price("9,50 €", "mittel")], markers: foodMarkers },
      { number: "112", name: "Pizza Mais", description: "Broccoli, Mais, Zwiebeln, Spinat und Tomatensoße", prices: [price("8,00 €", "24 cm"), price("9,00 €", "28 cm"), price("15,00 €", "40 cm")], markers: foodMarkers, vegetarian: true },
      { number: "113", name: "Pizza Vier Jahreszeiten", description: "Salami, Schinken, Mais, Paprika und Champignons", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers },
      { number: "114", name: "Pizza Bico", description: "Tomatensoße, Käse, Schafskäse, Ei, Broccoli und Spinat", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers, vegetarian: true },
      { number: "115", name: "Pizza Mozzarella", description: "Tomatensoße, Käse, Broccoli, Spinat und Mozzarella", prices: [price("8,00 €", "24 cm"), price("9,00 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers, vegetarian: true },
      { number: "116", name: "Pizza Mozzarella-Tomate", description: "Tomatensoße, Käse, frische Tomaten und Mozzarella", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers, vegetarian: true },
      { number: "117", name: "Pizza Kelly", description: "Tomatensoße, Broccoli, Champignons, Paprika, Tomaten und Käse", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers, vegetarian: true },
      { number: "118", name: "Pizza Meeresfrüchte", description: "Tomatensoße, Meeresfrüchte, Knoblauch und Käse", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers },
      { number: "119", name: "Pizza Oberdorla", description: "Tomatensoße, Käse, Salami, Schinken, Thunfisch, Champignons, Peperoni und Mais", prices: [price("8,50 €", "24 cm"), price("10,00 €", "28 cm"), price("16,50 €", "40 cm")], markers: foodMarkers },
      { number: "120", name: "Pizza Milano", description: "Tomatensoße, Thunfisch, Ei und Käse", prices: [price("8,00 €", "24 cm"), price("9,00 €", "28 cm"), price("15,00 €", "40 cm")], markers: foodMarkers },
      { number: "121", name: "Pizza Paradiso", description: "Tomatensoße, Salami, Schinken, Ananas, Peperoni und Käse", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers },
      { number: "122", name: "Pizza Langula", description: "Tomatensoße, Salami, Schinken, Gyros, Ei und Käse", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("16,00 €", "40 cm")], markers: foodMarkers },
      { number: "123", name: "Pizza Broccoli", description: "Sauce Hollandaise, Schinken, Broccoli, Paprika und Käse", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers },
      { number: "124", name: "Pizza Heyerode", description: "Sauce Hollandaise, Broccoli, Dönerfleisch und Käse", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("16,00 €", "40 cm")], markers: foodMarkers },
      { number: "125", name: "Pizza Fantasia", description: "Tomatensoße, Käse, Salami, Schinken, Thunfisch, Peperoni und Zwiebeln", prices: [price("8,00 €", "24 cm"), price("9,00 €", "28 cm"), price("16,00 €", "40 cm")], markers: foodMarkers },
      { number: "126", name: "Pizza Al Capone", description: "Tomatensoße, Käse, Schinken, Artischocken und scharfe Peperoniwurst", prices: [price("7,50 €", "24 cm"), price("8,50 €", "28 cm"), price("15,00 €", "40 cm")], markers: foodMarkers },
      { number: "127", name: "Pizza Mafia", description: "Tomatensoße, Käse, Schinken, Zwiebeln, Knoblauch und scharfer Pfeffer", prices: [price("8,00 €", "24 cm"), price("9,00 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers },
      { number: "128", name: "Pizza Capricciosa", description: "Tomatensoße, Käse, Salami, Champignons, Paprika und Peperoniwurst", prices: [price("8,50 €", "24 cm"), price("9,00 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers },
      { number: "129", name: "Pizza Tonno", description: "Tomatensoße, Käse, Thunfisch und Zwiebel", prices: [price("8,00 €", "24 cm"), price("9,00 €", "28 cm"), price("15,00 €", "40 cm")], markers: foodMarkers },
      { number: "130", name: "Pizza Hähnchen", description: "Hähnchenbruststreifen, Salami und Peperoni", prices: [price("8,00 €", "24 cm"), price("9,00 €", "28 cm"), price("15,00 €", "40 cm")], markers: foodMarkers },
      { number: "131", name: "Pizza Sizilia", description: "Hähnchenbruststreifen, Broccoli, Paprika, Zwiebeln und Champignons", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("16,00 €", "40 cm")], markers: foodMarkers },
      { number: "132", name: "Pizza Niederdorla", description: "Hähnchenbruststreifen, Zwiebeln und Bolognesesoße", prices: [price("8,00 €", "24 cm"), price("9,00 €", "28 cm"), price("15,00 €", "40 cm")], markers: foodMarkers },
      { number: "133", name: "Pizza O sole mio", description: "Tomatensoße, Käse, Salami, Schinken, Champignons und Ei", prices: [price("8,00 €", "24 cm"), price("9,00 €", "28 cm"), price("15,00 €", "40 cm")], markers: foodMarkers },
      { number: "134", name: "Pizza Boss", description: "Tomatensoße, Käse, Salami, Schinken, Champignons, Ei und Fleischsoße", prices: [price("8,00 €", "24 cm"), price("9,50 €", "28 cm"), price("15,00 €", "40 cm")], markers: foodMarkers },
      { number: "135", name: "Pizza Kammerforst", description: "Tomatensoße, Käse, Thunfisch, Krabben und Knoblauch", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("15,00 €", "40 cm")], markers: foodMarkers },
      { number: "136", name: "Pizza Vegetarisch", description: "Tomatensoße, Käse, Zwiebeln, Champignons, Paprika und Artischocken", prices: [price("8,00 €", "24 cm"), price("9,00 €", "28 cm"), price("15,00 €", "40 cm")], markers: foodMarkers, vegetarian: true },
      { number: "137", name: "Pizza Würzfleisch", description: "Käse und Würzfleisch", prices: [price("8,00 €", "24 cm"), price("9,00 €", "28 cm"), price("15,00 €", "40 cm")], markers: foodMarkers },
      { number: "138", name: "Pizza Heval Art", description: "Tomatensoße, Käse, Champignons, Döner-Gyros, Zwiebeln und scharfe Würzung", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("16,00 €", "40 cm")], markers: foodMarkers },
      { number: "139", name: "Pizza Spaghetti", description: "Hackfleischsoße, Spaghetti und Käse", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("15,50 €", "40 cm")], markers: foodMarkers },
      { number: "140", name: "Pizza Diedorf", description: "Tomatensoße, Käse, Döner-Gyros, Spaghetti und Zwiebel", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("16,00 €", "40 cm")], markers: foodMarkers },
      { number: "140a", name: "Dönerpizza", description: "Tomatensoße, Käse, Dönerfleisch und Sauce nach Wahl: Zaziki oder Salatsauce", prices: [price("8,00 €", "24 cm"), price("9,00 €", "28 cm"), price("15,00 €", "40 cm")], markers: foodMarkers },
      { number: "140b", name: "Pizza Sucuk", description: "Tomatensoße, Käse und türkische Wurst", prices: [price("8,50 €", "24 cm"), price("9,50 €", "28 cm"), price("16,50 €", "40 cm")], markers: foodMarkers },
    ],
  },
  {
    slug: "familie",
    label: "Familienpizza",
    note: "40 × 60 cm. Jede weitere Zutat + 2,00 €.",
    items: [
      { number: "141", name: "Familienpizza", description: "Tomatensoße, Salami, Schinken und Käse", prices: [price("25,00 €")], markers: foodMarkers },
      { number: "142", name: "Familienpizza Käse", description: "Tomatensoße und Käse", prices: [price("22,00 €")], markers: foodMarkers, vegetarian: true },
      { number: "143", name: "Familienpizza Salami", description: "Tomatensoße, Käse und Salami", prices: [price("24,00 €")], markers: foodMarkers },
    ],
  },
  {
    slug: "schnitzel",
    label: "Schnitzel",
    items: [
      { number: "145", name: "Schnitzel mit Fladenbrot", description: "Salat und Sauce nach Wahl", prices: [price("7,50 €")], markers: foodMarkers },
      { number: "146", name: "Schnitzel Wiener Art", description: "Pommes, Salat und Zitrone", prices: [price("8,50 €")], markers: foodMarkers },
      { number: "147", name: "Schnitzel Wiener Art mit Setzei", description: "Pommes und Salat", prices: [price("9,00 €")], markers: foodMarkers },
      { number: "148", name: "Rahmschnitzel", description: "Pommes und Salat", prices: [price("9,00 €")], markers: foodMarkers },
      { number: "149", name: "Putenschnitzel", description: "Pommes und Sauce Hollandaise", prices: [price("9,00 €")], markers: foodMarkers },
      { number: "150", name: "Bologneseschnitzel", description: "Pommes, Salat, Sahne, Fleischsoße und Käse überbacken", prices: [price("10,00 €")], markers: foodMarkers },
      { number: "151", name: "Würzfleischschnitzel", description: "Kroketten, Salat, Würzfleisch und Käse überbacken", prices: [price("10,00 €")], markers: foodMarkers },
      { number: "152", name: "Schnitzel Mozzarella", description: "Kroketten oder Pommes, Salat, Mozzarella, frische Tomaten und Käse überbacken", prices: [price("10,00 €")], markers: foodMarkers },
      { number: "153", name: "Würzfleischschnitzel", description: "Kroketten, Salat, Würzfleisch und Sauce Hollandaise überbacken", prices: [price("10,00 €")], markers: foodMarkers },
      { number: "154", name: "Dönerschnitzel", description: "Kroketten oder Pommes, Salat, Dönerfleisch, Schafskäse und Käse überbacken", prices: [price("10,50 €")], markers: foodMarkers },
      { number: "155", name: "Zwiebelschnitzel", description: "Pommes und Salat", prices: [price("9,50 €")], markers: foodMarkers },
      { number: "156", name: "Champignonschnitzel", description: "Pommes und Salat", prices: [price("9,50 €")], markers: foodMarkers },
      { number: "157", name: "Zigeunerschnitzel", description: "Salat, Pommes oder Kroketten", prices: [price("9,50 €")], markers: foodMarkers },
      { number: "158", name: "Hawaiischnitzel", description: "Ananas, Pommes, Salat und Käse überbacken", prices: [price("10,00 €")], markers: foodMarkers },
    ],
  },
  {
    slug: "baguette",
    label: "Baguettes",
    note: "Zu jedem Baguette gibt es einen kleinen gemischten Salat.",
    items: [
      { number: "160", name: "Baguette Schinken", description: "Schinken und Käse", prices: [price("7,50 €")], markers: foodMarkers },
      { number: "161", name: "Baguette Salami", description: "Salami und Käse", prices: [price("7,50 €")], markers: foodMarkers },
      { number: "162", name: "Baguette Hawaii", description: "Schinken, Ananas und Käse", prices: [price("7,50 €")], markers: foodMarkers },
      { number: "163", name: "Baguette Vegetario", description: "Broccoli, Spinat, Ei und Käse", prices: [price("8,50 €")], markers: foodMarkers, vegetarian: true },
      { number: "164", name: "Baguette Tonno", description: "Thunfisch, Zwiebeln und Käse", prices: [price("7,50 €")], markers: foodMarkers },
      { number: "165", name: "Baguette Peppino", description: "Salami, Paprika, Peperoni und Käse", prices: [price("7,50 €")], markers: foodMarkers },
      { number: "166", name: "Baguette Gyros", description: "Gyros, Zwiebeln und Käse", prices: [price("8,00 €")], markers: foodMarkers },
      { number: "167", name: "Baguette Quattro", description: "Salami, Schinken, Zwiebeln und Peperoni", prices: [price("8,00 €")], markers: foodMarkers },
      { number: "168", name: "Baguette Ollé", description: "Salami, Schinken, Champignons, Paprika und Oliven", prices: [price("8,50 €")], markers: foodMarkers },
      { number: "169", name: "Baguette Cango", description: "Gyros, Fetakäse, Peperoni und Zwiebeln", prices: [price("8,50 €")], markers: foodMarkers },
      { number: "170", name: "Baguette Würzfleisch", description: "Würzfleisch und Käse", prices: [price("7,50 €")], markers: foodMarkers },
    ],
  },
  {
    slug: "getraenke",
    label: "Getränke",
    items: [
      { name: "Cola, Fanta, Sprite, Mezzo Mix", prices: [price("2,50 €", "0,5 l")] },
      { name: "Uludag", prices: [price("3,00 €", "0,5 l")] },
      { name: "Eistee", prices: [price("2,50 €", "0,5 l")] },
      { name: "Wasser", prices: [price("2,00 €", "0,5 l")] },
      { name: "Ayran", prices: [price("2,00 €")] },
      { name: "Uludag", prices: [price("4,00 €", "1,0 l")] },
      { name: "Cola, Fanta, Sprite", prices: [price("3,50 €", "1,0 l")] },
      { name: "Hasseröder", prices: [price("2,50 €", "0,5 l")] },
      { name: "Beck’s", prices: [price("2,50 €", "0,5 l")] },
      { name: "Efes", prices: [price("2,50 €", "0,5 l")] },
      { name: "Lambrusco", prices: [price("6,00 €", "0,75 l")] },
    ],
  },
];

export const totalMenuItems = menuCategories.reduce(
  (total, category) => total + category.items.length,
  0,
);
